# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 20

[[main]]
  name = "Tools"
  weight = 25

[[main]]
  name = "What Is My IP?"
  parent = "Tools"
  url = "https://titik.xyz"
  weight = 25

[[main]]
  name = "Whois Bot"
  parent = "Tools"
  url = "https://t.me/"
  weight = 25

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/ikanbwl"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/iqbwl"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 20
